// Generated by gencpp from file digit_segmentation/floatArray.msg
// DO NOT EDIT!


#ifndef DIGIT_SEGMENTATION_MESSAGE_FLOATARRAY_H
#define DIGIT_SEGMENTATION_MESSAGE_FLOATARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace digit_segmentation
{
template <class ContainerAllocator>
struct floatArray_
{
  typedef floatArray_<ContainerAllocator> Type;

  floatArray_()
    : header()
    , type()
    , rotation(0.0)
    , translation()  {
    }
  floatArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(_alloc)
    , rotation(0.0)
    , translation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef double _rotation_type;
  _rotation_type rotation;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _translation_type;
  _translation_type translation;





  typedef boost::shared_ptr< ::digit_segmentation::floatArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::digit_segmentation::floatArray_<ContainerAllocator> const> ConstPtr;

}; // struct floatArray_

typedef ::digit_segmentation::floatArray_<std::allocator<void> > floatArray;

typedef boost::shared_ptr< ::digit_segmentation::floatArray > floatArrayPtr;
typedef boost::shared_ptr< ::digit_segmentation::floatArray const> floatArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::digit_segmentation::floatArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::digit_segmentation::floatArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::digit_segmentation::floatArray_<ContainerAllocator1> & lhs, const ::digit_segmentation::floatArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.rotation == rhs.rotation &&
    lhs.translation == rhs.translation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::digit_segmentation::floatArray_<ContainerAllocator1> & lhs, const ::digit_segmentation::floatArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace digit_segmentation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::digit_segmentation::floatArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::digit_segmentation::floatArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::digit_segmentation::floatArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::digit_segmentation::floatArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::digit_segmentation::floatArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::digit_segmentation::floatArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::digit_segmentation::floatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ae8a1a1538beabbdecb82544adb51e8";
  }

  static const char* value(const ::digit_segmentation::floatArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ae8a1a1538beabbULL;
  static const uint64_t static_value2 = 0xdecb82544adb51e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::digit_segmentation::floatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "digit_segmentation/floatArray";
  }

  static const char* value(const ::digit_segmentation::floatArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::digit_segmentation::floatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string type\n"
"float64 rotation\n"
"float64[] translation\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::digit_segmentation::floatArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::digit_segmentation::floatArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.rotation);
      stream.next(m.translation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct floatArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::digit_segmentation::floatArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::digit_segmentation::floatArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "rotation: ";
    Printer<double>::stream(s, indent + "  ", v.rotation);
    s << indent << "translation[]" << std::endl;
    for (size_t i = 0; i < v.translation.size(); ++i)
    {
      s << indent << "  translation[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.translation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIGIT_SEGMENTATION_MESSAGE_FLOATARRAY_H
