# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ur5e_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - finger_middle_joint_1
    - palm_finger_1_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur5e_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - finger_middle_joint_1
  - name: gripper_mode_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - palm_finger_1_joint
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_middle_joint_1
  gains:
    finger_middle_joint_1:
      p: 30 #100
      d: 1
      i: 0.1 #1
      i_clamp: 1
gripper_mode_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - palm_finger_1_joint
  gains:
    palm_finger_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ur5e_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 1000
      d: 50
      i: 10
      i_clamp: 100
    shoulder_lift_joint:
      p: 5000
      d: 30
      i: 100
      i_clamp: 400
    elbow_joint:
      p: 5000
      d: 50
      i: 10
      i_clamp: 100
    wrist_1_joint:
      p: 200
      d: 20
      i: 10
      i_clamp: 100
    wrist_2_joint:
      p: 100
      d: 10
      i: 0.1
      i_clamp: 100
    wrist_3_joint:
      p: 10
      d: 1
      i: 0.1
      i_clamp: 100
